service: testeLeveSaude

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1

plugins:
  - serverless-offline
  
functions:
  getAgendas:
    handler: dist/agenda/controller.getAgendas
    events:
      - http:
          path: agendas
          method: get
          
  postAgendamento:
    handler: dist/agendamento/controller.postAgendamento
    events:
      - http:
          path: agendamento
          method: post
